services:
   frontend:
      build:
         context: ./client
         dockerfile: Dockerfile
      ports:
         - "4173:4173"
      volumes:
         - ./client:/app/frontend
         - frontend_node_modules:/app/frontend/node_modules
      environment:
         - CHOKIDAR_USEPOLLING=true
         - VITE_API_URL=http://backend:8080

   backend:
      build:
         context: ./server
         dockerfile: Dockerfile
      ports:
         - "8080:8080"
      volumes:
         - ./server/src:/app/src
         - ./server/target:/app/target
         - backend_node_modules:/app/node_modules
      environment:
         - JAVA_OPTS=-Xms512m -Xmx1024m
         - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-ctr5oea3esus73b9lna0-a.singapore-postgres.render.com:5432/course_management_2stc
         - SPRING_DATASOURCE_USERNAME=course_management_2stc_user
         - SPRING_DATASOURCE_PASSWORD=gRaO8m2VmSX0tZwaNSzGXiuoBZGIGbnz

volumes:
   frontend_node_modules:
   backend_node_modules:
